# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

[[constraint]]
  name = "github.com/sirupsen/logrus"
  revision = "v1.2.0"

[[constraint]]
  name = "k8s.io/client-go"
  revision = "kubernetes-1.12.6"

[[constraint]]
  name = "k8s.io/apimachinery"
  revision = "kubernetes-1.12.6"

[[constraint]]
  name = "k8s.io/api"
  revision = "kubernetes-1.12.6"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  revision = "kubernetes-1.12.6"

[[constraint]]
  name = "github.com/coreos/etcd-operator"
  revision = "v0.9.4"

[[constraint]]
  name = "github.com/cloudflare/cfssl"
  revision = "1.3.2"

[[constraint]]
  name = "github.com/spf13/cobra"
  revision = "v0.0.3"

[[constraint]]
  name = "github.com/spf13/viper"
  revision = "v1.3.2"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
